# Generated by Django 5.2.2 on 2025-06-12 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("video_comment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45)),
                ("session_key", models.CharField(max_length=40)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_tracks",
                        to="video_comment.video",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["video", "ip_address"],
                        name="viewTracker_video_i_eb6149_idx",
                    ),
                    models.Index(
                        fields=["video", "user"], name="viewTracker_video_i_a28907_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("video", "user"),
                        name="unique_user_video_view",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("video", "ip_address", "session_key"),
                        name="unique_anonymous_video_view",
                    ),
                ],
            },
        ),
    ]
